# LAB 13

# Numpy

In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)
print(arr.shape) # (2, 3) → 2 rows, 3 columns
print(arr.ndim)#dimension of array

6
(2, 3)
2


In [3]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)
print("Original shape:", arr.shape)

# Reshape to a 2D array (2 rows, 3 columns)
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
print("New shape:", reshaped_arr.shape)

Original array: [1 2 3 4 5 6]
Original shape: (6,)
[[1 2 3]
 [4 5 6]]
New shape: (2, 3)


In [6]:
a = np.zeros((2, 3))  #Creates an array filled with zeros.
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
b = np.ones((3, 2), dtype=int)  #Creates an array filled with ones.
print(b)

[[1 1]
 [1 1]
 [1 1]]


In [9]:
c = np.random.random((2, 2))  #Generates random numbers between 0 and 1
print(c)

[[0.17124624 0.72070631]
 [0.09750451 0.79154425]]


In [10]:
d = np.random.randint(1, 10, (2, 2))  #random numbers from a range
print(d)

[[7 9]
 [2 3]]


In [11]:
e = np.indices((2, 3))  #Creates a grid of indices
print(e)

[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]


In [16]:
def pythonsum(n):
    a = list(range(n))   # convert to list
    b = list(range(n))   # convert to list
    c = []
    for i in range(n):
        a[i] = i ** 2    # square
        b[i] = i ** 3    # cube
        c.append(a[i] + b[i])  # sum
    return c
print(pythonsum(5))

[0, 2, 12, 36, 80]


In [18]:
def pythonsum(n):
    a = [0] * n   # list of n zeros
    b = [0] * n   # list of n zeros
    c = []
    for i in range(n):
        a[i] = i ** 2   # store square of i
        b[i] = i ** 3   # store cube of i
        c.append(a[i] + b[i])  # sum of square + cube
    return c

print(pythonsum(5))

[0, 2, 12, 36, 80]


In [19]:
import numpy as np
def numpysum(n):
  a = np.arange(n) ** 2  #Creates an array [0,1,..n-1] and element-wise sqauring
  b = np.arange(n) ** 3
  c = a + b #element wise adding - NO LOOP Overhead, hence Memory Efficient
  return c

In [20]:
numpysum(3)

array([ 0,  2, 12])

In [21]:
#Creating Arrays from Sequences
#a list of numbers will create a 1D array,
#a list of lists will create a 2D array,
#further nested lists will create higher-dimensional arrays. 
#In general, any array object is called an ndarray in NumPy.

In [22]:
import numpy as np
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [23]:
import numpy as np
np.array([127, 128, 129], dtype=np.int32) 

array([127, 128, 129], dtype=int32)

In [25]:
#ARRAY CREATION FUNCTIONS
import numpy as np
np.arange(10) #0 TO BEFORE 10, Step Value 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(2, 10, dtype=float) # Creates an array starting from 2.0 up to (but not including) 10.0
                              # Default step = 1.0 because dtype=float

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [28]:
np.arange(2, 3, 0.1) # Creates an array starting from 2.0 up to (but not including) 3.0
                     # Step size = 0.1

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

#best practice for numpy.arange is to use integer start, end, and step values.

In [30]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
# np.linspace(1.0, 4.0, 6) generates 6 equally spaced values from 1.0 to 4.0 (both included).
# It divides the range into 5 equal intervals: [1. , 1.6, 2.2, 2.8, 3.4, 4. ]

In [6]:
#Vandermonde Matrix
import numpy as np
np.vander(np.linspace(0, 2, 5), 2)#Creates 5 values between 0 and 2

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [7]:
np.vander([1, 2, 3, 4], 2)# Builds a Vandermonde matrix with input [1, 2, 3, 4] and 2 columns

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [5]:
np.vander((1, 2, 3, 4), 4)# Builds a Vandermonde matrix with input (1,2,3,4) and 4 columns(powers from 3 down to 0)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

| Code                                 | Shape    | Meaning                                           |
| ------------------------------------ | -------- | ------------------------------------------------- |
| `np.vander(np.linspace(0, 2, 5), 2)` | `(5, 2)` | 2-column Vandermonde matrix of `[0, 0.5, ..., 2]` |
| `np.vander([1, 2, 3, 4], 2)`         | `(4, 2)` | Powers: `[x, 1]` for each x                       |
| `np.vander((1, 2, 3, 4), 4)`         | `(4, 4)` | Powers: `[x**3, x**2, x, 1]`                      |
